---
abstract: 'Serve static files from document root with directory index template'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Directory-Template
requires:
  File::ShareDir: 1.00
  Plack::Middleware::TemplateToolkit: 0.26
  perl: v5.10.1
resources:
  bugtracker: https://github.com/nichtich/Plack-App-Directory-Template/issues
  homepage: https://github.com/nichtich/Plack-App-Directory-Template
  repository: https://github.com/nichtich/Plack-App-Directory-Template.git
version: 0.2
